name: Test

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2.5.0
        with:
          node-version: 'lts/*'

      - run: npm install
      - run: npm test
